import { FAFixture } from './types';

// ==========================================================
// OFFICIAL FA FULL-TIME FIXTURES (SCOTTER UNITED JFC)
// Season ID: 451104307 | Club ID: 837952594
// Fixtures prior to 12 September 2026 (Pre-Season & Early League Kickoff)
// Fixtures from 12 Sep onwards have been removed per club instructions.
// ==========================================================

export const RAW_MOCK_FA_FULLTIME_FIXTURES: FAFixture[] = [
  // ==========================================================
  // PRE-SEASON MATCHDAY 1: Saturday 29 August 2026 (Archived / Previous)
  // ==========================================================
  {
    id: 'fa-ps-0829-1',
    date: '2026-08-29',
    timeSlot: '09:45',
    pitchId: '5v5',
    homeTeam: 'Scotter United U7 Juniors',
    awayTeam: 'Gainsborough Trinity U7s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U7 Juniors',
  },
  {
    id: 'fa-ps-0829-2',
    date: '2026-08-29',
    timeSlot: '10:45',
    pitchId: '5v5',
    homeTeam: 'Scotter United U7 Saints',
    awayTeam: 'Messingham Juniors U7s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U7 Saints',
  },
  {
    id: 'fa-ps-0829-3',
    date: '2026-08-29',
    timeSlot: '11:45',
    pitchId: '5v5',
    homeTeam: 'Scotter United U8 Juniors',
    awayTeam: 'Barton Town U8s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U8 Juniors',
  },
  {
    id: 'fa-ps-0829-4',
    date: '2026-08-29',
    timeSlot: '12:45',
    pitchId: '5v5',
    homeTeam: 'Scotter United U8 Saints',
    awayTeam: 'Kirton Lindsey U8s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U8 Saints',
  },
  {
    id: 'fa-ps-0829-5',
    date: '2026-08-29',
    timeSlot: '13:45',
    pitchId: '5v5',
    homeTeam: 'Scotter United U9 Juniors',
    awayTeam: 'Bottesford Town U9s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U9 Juniors',
  },
  {
    id: 'fa-ps-0829-6',
    date: '2026-08-29',
    timeSlot: '09:30',
    pitchId: '7v7',
    homeTeam: 'Scotter United U10 Juniors',
    awayTeam: 'Winterton Rangers U10s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U10 Juniors',
  },
  {
    id: 'fa-ps-0829-7',
    date: '2026-08-29',
    timeSlot: '10:45',
    pitchId: '7v7',
    homeTeam: 'Scotter United U10 Saints',
    awayTeam: 'Epworth Town U10s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U10 Saints',
  },
  {
    id: 'fa-ps-0829-8',
    date: '2026-08-29',
    timeSlot: '12:00',
    pitchId: '7v7',
    homeTeam: 'Scotter United U11 Colts',
    awayTeam: 'Grimsby Town U11s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U11 Colts',
  },
  {
    id: 'fa-ps-0829-9',
    date: '2026-08-29',
    timeSlot: '13:30',
    pitchId: '7v7',
    homeTeam: 'Scotter United U11 Saints',
    awayTeam: 'Dale Park U11s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U11 Saints',
  },
  {
    id: 'fa-ps-0829-10',
    date: '2026-08-29',
    timeSlot: '09:30',
    pitchId: '9v9',
    homeTeam: 'Scotter United U12 Juniors',
    awayTeam: 'Gainsborough Trinity U12s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U12 Juniors',
  },
  {
    id: 'fa-ps-0829-11',
    date: '2026-08-29',
    timeSlot: '11:00',
    pitchId: '9v9',
    homeTeam: 'Scotter United U12 Colts',
    awayTeam: 'Messingham Juniors U12s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U12 Colts',
  },
  {
    id: 'fa-ps-0829-12',
    date: '2026-08-29',
    timeSlot: '10:00',
    pitchId: '11v11',
    homeTeam: 'Scotter United U14s',
    awayTeam: 'Bottesford Town U14s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U14s',
  },
  {
    id: 'fa-ps-0829-14',
    date: '2026-08-29',
    timeSlot: '12:00',
    pitchId: '11v11',
    homeTeam: 'Scotter United U15',
    awayTeam: 'App-Frod U15s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U15',
  },
  {
    id: 'fa-ps-0829-13',
    date: '2026-08-29',
    timeSlot: '14:00',
    pitchId: '11v11',
    homeTeam: 'Scotter United U14 Girls',
    awayTeam: 'Louth Girls U14',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U14 Girls',
  },

  // Sunday 30 August 2026 (Archived / Previous)
  {
    id: 'fa-ps-0830-1',
    date: '2026-08-30',
    timeSlot: '10:30',
    pitchId: '11v11',
    homeTeam: 'Scotter United U18',
    awayTeam: 'Lincoln United U18s',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United U18',
  },
  {
    id: 'fa-ps-0830-2',
    date: '2026-08-30',
    timeSlot: '12:30',
    pitchId: '11v11',
    homeTeam: 'Scotter United Vets',
    awayTeam: 'Ruston Sports Vets',
    competition: 'Pre-Season Friendly',
    scotterTeam: 'Scotter United Vets',
  },

  // ==========================================================
  // PRE-SEASON MATCHDAY 2: Saturday 05 September 2026 (Archived / Previous)
  // ==========================================================
  {
    id: 'fa-ps-0905-1',
    date: '2026-09-05',
    timeSlot: '09:45',
    pitchId: '5v5',
    homeTeam: 'Scotter United U7 Juniors',
    awayTeam: 'Kirton Lindsey U7s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U7 Juniors',
  },
  {
    id: 'fa-ps-0905-2',
    date: '2026-09-05',
    timeSlot: '10:45',
    pitchId: '5v5',
    homeTeam: 'Scotter United U7 Saints',
    awayTeam: 'Crosby United U7s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U7 Saints',
  },
  {
    id: 'fa-ps-0905-3',
    date: '2026-09-05',
    timeSlot: '11:45',
    pitchId: '5v5',
    homeTeam: 'Scotter United U8 Juniors',
    awayTeam: 'Messingham Juniors U8s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U8 Juniors',
  },
  {
    id: 'fa-ps-0905-4',
    date: '2026-09-05',
    timeSlot: '12:45',
    pitchId: '5v5',
    homeTeam: 'Scotter United U8 Saints',
    awayTeam: 'Brigg Town U8s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U8 Saints',
  },
  {
    id: 'fa-ps-0905-5',
    date: '2026-09-05',
    timeSlot: '13:45',
    pitchId: '5v5',
    homeTeam: 'Scotter United U9 Saints',
    awayTeam: 'Crosby United U9s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U9 Saints',
  },
  {
    id: 'fa-ps-0905-6',
    date: '2026-09-05',
    timeSlot: '09:30',
    pitchId: '7v7',
    homeTeam: 'Scotter United U10 Juniors',
    awayTeam: 'Dale Park U10s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U10 Juniors',
  },
  {
    id: 'fa-ps-0905-7',
    date: '2026-09-05',
    timeSlot: '10:45',
    pitchId: '7v7',
    homeTeam: 'Scotter United U10 Saints',
    awayTeam: 'Bottesford Town U10s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U10 Saints',
  },
  {
    id: 'fa-ps-0905-8',
    date: '2026-09-05',
    timeSlot: '12:00',
    pitchId: '7v7',
    homeTeam: 'Scotter United U11 Saints',
    awayTeam: 'Dale Park U11s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U11 Saints',
  },
  {
    id: 'fa-ps-0905-9',
    date: '2026-09-05',
    timeSlot: '13:30',
    pitchId: '7v7',
    homeTeam: 'Scotter United U11 Juniors',
    awayTeam: 'Brigg Town U11s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U11 Juniors',
  },
  {
    id: 'fa-ps-0905-10',
    date: '2026-09-05',
    timeSlot: '09:30',
    pitchId: '9v9',
    homeTeam: 'Scotter United U12 Juniors',
    awayTeam: 'Barton Town U12s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U12 Juniors',
  },
  {
    id: 'fa-ps-0905-11',
    date: '2026-09-05',
    timeSlot: '11:00',
    pitchId: '9v9',
    homeTeam: 'Scotter United U12 Colts',
    awayTeam: 'Epworth Town U12s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U12 Colts',
  },
  {
    id: 'fa-ps-0905-12',
    date: '2026-09-05',
    timeSlot: '12:30',
    pitchId: '9v9',
    homeTeam: 'Scotter United U13 Saints',
    awayTeam: 'Kirton Lindsey U13s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U13 Saints',
  },
  {
    id: 'fa-ps-0905-13',
    date: '2026-09-05',
    timeSlot: '10:00',
    pitchId: '11v11',
    homeTeam: 'Scotter United U14s',
    awayTeam: 'Grimsby Borough U14s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U14s',
  },
  {
    id: 'fa-ps-0905-15',
    date: '2026-09-05',
    timeSlot: '12:00',
    pitchId: '11v11',
    homeTeam: 'Scotter United U15',
    awayTeam: 'Bottesford Town U15s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U15',
  },
  {
    id: 'fa-ps-0905-14',
    date: '2026-09-05',
    timeSlot: '14:00',
    pitchId: '11v11',
    homeTeam: 'Scotter United U14 Girls',
    awayTeam: 'Grimsby Borough Girls U14',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U14 Girls',
  },

  // Sunday 06 September 2026 (Archived / Previous)
  {
    id: 'fa-ps-0906-1',
    date: '2026-09-06',
    timeSlot: '10:30',
    pitchId: '11v11',
    homeTeam: 'Scotter United U18',
    awayTeam: 'Cleethorpes Town U18s',
    competition: 'Jack Kalson Warm-up Trophy',
    scotterTeam: 'Scotter United U18',
  },
  {
    id: 'fa-ps-0906-2',
    date: '2026-09-06',
    timeSlot: '12:30',
    pitchId: '11v11',
    homeTeam: 'Scotter United Vets',
    awayTeam: 'Appleby Frodingham Vets',
    competition: 'Lincs County Veterans League',
    scotterTeam: 'Scotter United Vets',
  },

  // ==========================================================
  // MIDWEEK FIXTURES: Wednesday 09 September 2026 (Current / Upcoming)
  // ==========================================================
  {
    id: 'fa-cur-0909-1',
    date: '2026-09-09',
    timeSlot: '18:00',
    pitchId: '9v9',
    homeTeam: 'Scotter United U12 Juniors',
    awayTeam: 'Gainsborough Trinity U12s',
    competition: 'Midweek Cup Preliminary',
    scotterTeam: 'Scotter United U12 Juniors',
  },
  {
    id: 'fa-cur-0909-2',
    date: '2026-09-09',
    timeSlot: '18:30',
    pitchId: '11v11',
    homeTeam: 'Scotter United U14s',
    awayTeam: 'Bottesford Town U14s',
    competition: 'Midweek Cup Preliminary',
    scotterTeam: 'Scotter United U14s',
  },

  // ==========================================================
  // FRIDAY FIXTURES: Friday 11 September 2026 (Current / Upcoming)
  // ==========================================================
  {
    id: 'fa-cur-0911-1',
    date: '2026-09-11',
    timeSlot: '18:00',
    pitchId: '7v7',
    homeTeam: 'Scotter United U11 Juniors',
    awayTeam: 'Brigg Town U11s',
    competition: 'Junior League Opener',
    scotterTeam: 'Scotter United U11 Juniors',
  },
  {
    id: 'fa-cur-0911-2',
    date: '2026-09-11',
    timeSlot: '18:30',
    pitchId: '11v11',
    homeTeam: 'Scotter United U15',
    awayTeam: 'App-Frod U15s',
    competition: 'Junior League Opener',
    scotterTeam: 'Scotter United U15',
  }
];
